/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeSort */

#ifndef _Included_NativeSort
#define _Included_NativeSort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeSort
 * Method:    sort01
 * Signature: ([Ljava/lang/Double;Ljava/lang/Boolean;)[Ljava/lang/Double;
 */
JNIEXPORT jobjectArray JNICALL Java_NativeSort_sort01
  (JNIEnv *, jobject, jobjectArray, jobject);

/*
 * Class:     NativeSort
 * Method:    sort02
 * Signature: ([Ljava/lang/Double;)[Ljava/lang/Double;
 */
JNIEXPORT jobjectArray JNICALL Java_NativeSort_sort02
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     NativeSort
 * Method:    sort03
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_NativeSort_sort03
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
